export const Modal = {
  weekdays: [
    { weekday: "П", selected: false },
    { weekday: "В", selected: false },
    { weekday: "С", selected: false },
    { weekday: "Ч", selected: false },
    { weekday: "П", selected: false },
    { weekday: "С", selected: false },
    { weekday: "В", selected: false },
  ],
  dropdown: ["Категория", "Товар"],
  discountTypes: ["1+1", "2+1", "Сумма чека", "По промокоду"],
  period: "00.00.0000 - 00.00.0000",
  categories: ["Полуфабрикаты", "Напитки", "Корм для животных"],
  products: ["Винегрет", "Snickers", "Пельмени Цезарь"],
  desc: "Состав креветки (Pandalus borealis), вода (защитная глазурь). Краткое описание Варено-мороженые водные беспозвоночные. Глазурь не более 14%. Зона вылова: Северные районы Атлантического океана.",
  product: { article: "000000", name: null, discount: 0 },
  discountPercents: [10, 20, 30, 40],
  productsCount: 19783,
  discountsCount: 19783,
  address: "г. Минск ул Беломорская дом 7",
  statusFilter: "Активные",
  user: {
    name: "Владимировна И.А.",
    position: "Администратор",
  },
  notifications: 3,
};
